# Change these first
owner: searxng # Your GitHub organization or username, where this repository lives
repo: searx-instances-uptime # The name of this repository
sites:
  - name: searx.space
    url: https://searx.space
  - name: baresearch.org
    url: https://baresearch.org
  - name: copp.gg
    url: https://copp.gg
  - name: darmarit.org
    url: https://darmarit.org/searx
  - name: etsi.me
    url: https://etsi.me
  - name: fairsuch.net
    url: https://fairsuch.net
  - name: nogoo.me
    url: https://nogoo.me
  - name: northboot.xyz
    url: https://northboot.xyz
  - name: nyc1.sx.ggtyler.dev
    url: https://nyc1.sx.ggtyler.dev
  - name: ooglester.com
    url: https://ooglester.com
  - name: opnxng.com
    url: https://opnxng.com
  - name: paulgo.io
    url: https://paulgo.io
  - name: priv.au
    url: https://priv.au
  - name: s.mble.dk
    url: https://s.mble.dk
  - name: s.trung.fun
    url: https://s.trung.fun
  - name: search.blitzw.in
    url: https://search.blitzw.in
  - name: search.bus-hit.me
    url: https://search.bus-hit.me
  - name: search.canine.tools
    url: https://search.canine.tools
  - name: search.charliewhiskey.net
    url: https://search.charliewhiskey.net
  - name: search.citw.lgbt
    url: https://search.citw.lgbt
  - name: search.datura.network
    url: https://search.datura.network
  - name: search.dotone.nl
    url: https://search.dotone.nl
  - name: search.einfachzocken.eu
    url: https://search.einfachzocken.eu
  - name: search.fredix.xyz
    url: https://search.fredix.xyz
  - name: search.gcomm.ch
    url: https://search.gcomm.ch
  - name: search.hbubli.cc
    url: https://search.hbubli.cc
  - name: search.im-in.space
    url: https://search.im-in.space
  - name: search.incogniweb.net
    url: https://search.incogniweb.net
  - name: search.indst.eu
    url: https://search.indst.eu
  - name: search.inetol.net
    url: https://search.inetol.net
  - name: search.leptons.xyz
    url: https://search.leptons.xyz
  - name: search.mdosch.de
    url: https://search.mdosch.de
  - name: search.nadeko.net
    url: https://search.nadeko.net
  - name: search.nerdvpn.de
    url: https://search.nerdvpn.de
  - name: search.ngn.tf
    url: https://search.ngn.tf
  - name: search.nordh.tech
    url: https://search.nordh.tech
  - name: search.ononoki.org
    url: https://search.ononoki.org
  - name: search.privacyredirect.com
    url: https://search.privacyredirect.com
  - name: search.projectsegfau.lt
    url: https://search.projectsegfau.lt
  - name: search.rhscz.eu
    url: https://search.rhscz.eu
  - name: search.rowie.at
    url: https://search.rowie.at
  - name: search.sapti.me
    url: https://search.sapti.me
  - name: search.smnz.de
    url: https://search.smnz.de
  - name: search.tommy-tran.com
    url: https://search.tommy-tran.com
  - name: searx.aleteoryx.me
    url: https://searx.aleteoryx.me
  - name: searx.ankha.ac
    url: https://searx.ankha.ac
  - name: searx.be
    url: https://searx.be
  - name: searx.colbster937.dev
    url: https://searx.colbster937.dev
  - name: searx.daetalytica.io
    url: https://searx.daetalytica.io
  - name: searx.dresden.network
    url: https://searx.dresden.network
  - name: searx.electroncash.de
    url: https://searx.electroncash.de
  - name: searx.foss.family
    url: https://searx.foss.family
  - name: searx.hu
    url: https://searx.hu
  - name: searx.juancord.xyz
    url: https://searx.juancord.xyz
  - name: searx.lunar.icu
    url: https://searx.lunar.icu
  - name: searx.mv-software.de
    url: https://searx.mv-software.de
  - name: searx.mxchange.org
    url: https://searx.mxchange.org
  - name: searx.namejeff.xyz
    url: https://searx.namejeff.xyz
  - name: searx.nobulart.com
    url: https://searx.nobulart.com
  - name: searx.numeriquement.fr
    url: https://searx.numeriquement.fr
  - name: searx.oakleycord.dev
    url: https://searx.oakleycord.dev
  - name: searx.ox2.fr
    url: https://searx.ox2.fr
  - name: searx.perennialte.ch
    url: https://searx.perennialte.ch
  - name: searx.rhscz.eu
    url: https://searx.rhscz.eu
  - name: searx.ro
    url: https://searx.ro
  - name: searx.sev.monster
    url: https://searx.sev.monster
  - name: searx.thefloatinglab.world
    url: https://searx.thefloatinglab.world
  - name: searx.tiekoetter.com
    url: https://searx.tiekoetter.com
  - name: searx.tuxcloud.net
    url: https://searx.tuxcloud.net
  - name: searx.work
    url: https://searx.work
  - name: searx.zhenyapav.com
    url: https://searx.zhenyapav.com
  - name: searxng.brihx.fr
    url: https://searxng.brihx.fr
  - name: searxng.ch
    url: https://searxng.ch
  - name: searxng.hweeren.com
    url: https://searxng.hweeren.com
  - name: searxng.shreven.org
    url: https://searxng.shreven.org
  - name: searxng.site
    url: https://searxng.site
  - name: seek.fyi
    url: https://seek.fyi
  - name: skyrimhater.com
    url: https://skyrimhater.com
  - name: sx.ca.zorby.top
    url: https://sx.ca.zorby.top
  - name: sx.catgirl.cloud
    url: https://sx.catgirl.cloud
  - name: sx.thatxtreme.dev
    url: https://sx.thatxtreme.dev
  - name: sx.zorby.top
    url: https://sx.zorby.top
  - name: www.gruble.de
    url: https://www.gruble.de
  - name: www.jabber-germany.de
    url: https://www.jabber-germany.de/searx
  - name: xo.wtf
    url: https://xo.wtf
  - name: searx.neocities.org
    url: https://searx.neocities.org
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.searxng.org
  #baseUrl: /searx-instances-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SearXNG and SearX instances
  introTitle: "Uptime of SearXNG and SearX instances"
  introMessage: This status page monitors [SearXNG and SearX instances](https://github.com/searxng/searx-instances) for uptime.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
