# Change these first
owner: searxng # Your GitHub organization or username, where this repository lives
repo: searx-instances-uptime # The name of this repository
sites:
  - name: searx.space
    url: https://searx.space
  - name: baresearch.org
    url: https://baresearch.org
  - name: copp.gg
    url: https://copp.gg
  - name: darmarit.org
    url: https://darmarit.org/searx
  - name: etsi.me
    url: https://etsi.me
  - name: fairsuch.net
    url: https://fairsuch.net
  - name: find.xenorio.xyz
    url: https://find.xenorio.xyz
  - name: kantan.cat
    url: https://kantan.cat
  - name: metacat.online
    url: https://metacat.online
  - name: northboot.xyz
    url: https://northboot.xyz
  - name: nyc1.sx.ggtyler.dev
    url: https://nyc1.sx.ggtyler.dev
  - name: o5.gg
    url: https://o5.gg
  - name: ooglester.com
    url: https://ooglester.com
  - name: opnxng.com
    url: https://opnxng.com
  - name: paulgo.io
    url: https://paulgo.io
  - name: priv.au
    url: https://priv.au
  - name: s.mble.dk
    url: https://s.mble.dk
  - name: search.080609.xyz
    url: https://search.080609.xyz
  - name: search.2b9t.xyz
    url: https://search.2b9t.xyz
  - name: search.anoni.net
    url: https://search.anoni.net
  - name: search.ashisgreat.xyz
    url: https://search.ashisgreat.xyz
  - name: search.bladerunn.in
    url: https://search.bladerunn.in
  - name: search.buddyverse.net
    url: https://search.buddyverse.net
  - name: search.canine.tools
    url: https://search.canine.tools
  - name: search.catboy.house
    url: https://search.catboy.house
  - name: search.charliewhiskey.net
    url: https://search.charliewhiskey.net
  - name: search.einfachzocken.eu
    url: https://search.einfachzocken.eu
  - name: search.ethibox.fr
    url: https://search.ethibox.fr
  - name: search.hbubli.cc
    url: https://search.hbubli.cc
  - name: search.iguru.gr
    url: https://search.iguru.gr
  - name: search.im-in.space
    url: https://search.im-in.space
  - name: search.indst.eu
    url: https://search.indst.eu
  - name: search.inetol.net
    url: https://search.inetol.net
  - name: search.internetsucks.net
    url: https://search.internetsucks.net
  - name: search.ipsys.bf
    url: https://search.ipsys.bf
  - name: search.ipv6s.net
    url: https://search.ipv6s.net
  - name: search.leptons.xyz
    url: https://search.leptons.xyz
  - name: search.mdosch.de
    url: https://search.mdosch.de
  - name: search.nerdvpn.de
    url: https://search.nerdvpn.de
  - name: search.oh64.moe
    url: https://search.oh64.moe
  - name: search.ohaa.xyz
    url: https://search.ohaa.xyz
  - name: search.ononoki.org
    url: https://search.ononoki.org
  - name: search.perditum.com
    url: https://search.perditum.com
  - name: search.privacyredirect.com
    url: https://search.privacyredirect.com
  - name: search.projectsegfau.lt
    url: https://search.projectsegfau.lt
  - name: search.rhscz.eu
    url: https://search.rhscz.eu
  - name: search.rowie.at
    url: https://search.rowie.at
  - name: search.sapti.me
    url: https://search.sapti.me
  - name: search.system51.co.uk
    url: https://search.system51.co.uk
  - name: search.undertale.uk
    url: https://search.undertale.uk
  - name: search.url4irl.com
    url: https://search.url4irl.com
  - name: searx.ankha.ac
    url: https://searx.ankha.ac
  - name: searx.dresden.network
    url: https://searx.dresden.network
  - name: searx.foobar.vip
    url: https://searx.foobar.vip
  - name: searx.foss.family
    url: https://searx.foss.family
  - name: searx.juancord.xyz
    url: https://searx.juancord.xyz
  - name: searx.lunar.icu
    url: https://searx.lunar.icu
  - name: searx.mbuf.net
    url: https://searx.mbuf.net
  - name: searx.mxchange.org
    url: https://searx.mxchange.org
  - name: searx.namejeff.xyz
    url: https://searx.namejeff.xyz
  - name: searx.oloke.xyz
    url: https://searx.oloke.xyz
  - name: searx.ox2.fr
    url: https://searx.ox2.fr
  - name: searx.party
    url: https://searx.party
  - name: searx.perennialte.ch
    url: https://searx.perennialte.ch
  - name: searx.ppeb.me
    url: https://searx.ppeb.me
  - name: searx.rhscz.eu
    url: https://searx.rhscz.eu
  - name: searx.ro
    url: https://searx.ro
  - name: searx.sev.monster
    url: https://searx.sev.monster
  - name: searx.stream
    url: https://searx.stream
  - name: searx.tiekoetter.com
    url: https://searx.tiekoetter.com
  - name: searx.tuxcloud.net
    url: https://searx.tuxcloud.net
  - name: searx.zhenyapav.com
    url: https://searx.zhenyapav.com
  - name: searxng.biz
    url: https://searxng.biz
  - name: searxng.deliberate.world
    url: https://searxng.deliberate.world
  - name: searxng.f24o.zip
    url: https://searxng.f24o.zip
  - name: searxng.hweeren.com
    url: https://searxng.hweeren.com
  - name: searxng.shreven.org
    url: https://searxng.shreven.org
  - name: searxng.site
    url: https://searxng.site
  - name: searxng.website
    url: https://searxng.website
  - name: seek.fyi
    url: https://seek.fyi
  - name: sx.catgirl.cloud
    url: https://sx.catgirl.cloud
  - name: www.gruble.de
    url: https://www.gruble.de
  - name: searx.neocities.org
    url: https://searx.neocities.org
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.searxng.org
  #baseUrl: /searx-instances-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SearXNG and SearX instances
  introTitle: "Uptime of SearXNG and SearX instances"
  introMessage: This status page monitors [SearXNG and SearX instances](https://github.com/searxng/searx-instances) for uptime.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
