# Change these first
owner: searxng # Your GitHub organization or username, where this repository lives
repo: searx-instances-uptime # The name of this repository
commitMessages:
  commitAuthorName: "searxng-bot"
  commitAuthorEmail: "searxng-bot@users.noreply.github.com"
sites:
  - name: searx.space
    url: https://searx.space
  - name: baresearch.org
    url: https://baresearch.org
  - name: copp.gg
    url: https://copp.gg
  - name: etsi.me
    url: https://etsi.me
  - name: find.xenorio.xyz
    url: https://find.xenorio.xyz
  - name: grep.vim.wtf
    url: https://grep.vim.wtf
  - name: kantan.cat
    url: https://kantan.cat
  - name: o5.gg
    url: https://o5.gg
  - name: ooglester.com
    url: https://ooglester.com
  - name: opnxng.com
    url: https://opnxng.com
  - name: paulgo.io
    url: https://paulgo.io
  - name: priv.au
    url: https://priv.au
  - name: s.mble.dk
    url: https://s.mble.dk
  - name: search.2b9t.xyz
    url: https://search.2b9t.xyz
  - name: search.abohiccups.com
    url: https://search.abohiccups.com
  - name: search.anoni.net
    url: https://search.anoni.net
  - name: search.bladerunn.in
    url: https://search.bladerunn.in
  - name: search.catboy.house
    url: https://search.catboy.house
  - name: search.charliewhiskey.net
    url: https://search.charliewhiskey.net
  - name: search.darkness.services
    url: https://search.darkness.services
  - name: search.einfachzocken.eu
    url: https://search.einfachzocken.eu
  - name: search.ethibox.fr
    url: https://search.ethibox.fr
  - name: search.femboy.ad
    url: https://search.femboy.ad
  - name: search.freestater.org
    url: https://search.freestater.org
  - name: search.hbubli.cc
    url: https://search.hbubli.cc
  - name: search.im-in.space
    url: https://search.im-in.space
  - name: search.indst.eu
    url: https://search.indst.eu
  - name: search.inetol.net
    url: https://search.inetol.net
  - name: search.internetsucks.net
    url: https://search.internetsucks.net
  - name: search.ipsys.bf
    url: https://search.ipsys.bf
  - name: search.ipv6s.net
    url: https://search.ipv6s.net
  - name: search.mdosch.de
    url: https://search.mdosch.de
  - name: search.minus27315.dev
    url: https://search.minus27315.dev
  - name: search.oh64.moe
    url: https://search.oh64.moe
  - name: search.ononoki.org
    url: https://search.ononoki.org
  - name: search.privacyredirect.com
    url: https://search.privacyredirect.com
  - name: search.rhscz.eu
    url: https://search.rhscz.eu
  - name: search.rowie.at
    url: https://search.rowie.at
  - name: search.sapti.me
    url: https://search.sapti.me
  - name: search.undertale.uk
    url: https://search.undertale.uk
  - name: search.unredacted.org
    url: https://search.unredacted.org
  - name: search.url4irl.com
    url: https://search.url4irl.com
  - name: search.wdpserver.com
    url: https://search.wdpserver.com
  - name: search.zina.dev
    url: https://search.zina.dev
  - name: searx.ankha.ac
    url: https://searx.ankha.ac
  - name: searx.dresden.network
    url: https://searx.dresden.network
  - name: searx.lunar.icu
    url: https://searx.lunar.icu
  - name: searx.mbuf.net
    url: https://searx.mbuf.net
  - name: searx.mxchange.org
    url: https://searx.mxchange.org
  - name: searx.namejeff.xyz
    url: https://searx.namejeff.xyz
  - name: searx.oloke.xyz
    url: https://searx.oloke.xyz
  - name: searx.ox2.fr
    url: https://searx.ox2.fr
  - name: searx.party
    url: https://searx.party
  - name: searx.perennialte.ch
    url: https://searx.perennialte.ch
  - name: searx.rhscz.eu
    url: https://searx.rhscz.eu
  - name: searx.ro
    url: https://searx.ro
  - name: searx.sev.monster
    url: https://searx.sev.monster
  - name: searx.stream
    url: https://searx.stream
  - name: searx.tiekoetter.com
    url: https://searx.tiekoetter.com
  - name: searx.tuxcloud.net
    url: https://searx.tuxcloud.net
  - name: searxng.biz
    url: https://searxng.biz
  - name: searxng.canine.tools
    url: https://searxng.canine.tools
  - name: searxng.cups.moe
    url: https://searxng.cups.moe
  - name: searxng.shreven.org
    url: https://searxng.shreven.org
  - name: searxng.site
    url: https://searxng.site
  - name: searxng.website
    url: https://searxng.website
  - name: seek.fyi
    url: https://seek.fyi
  - name: sx.catgirl.cloud
    url: https://sx.catgirl.cloud
  - name: www.gruble.de
    url: https://www.gruble.de
  - name: searx.neocities.org
    url: https://searx.neocities.org
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.searxng.org
  #baseUrl: /searx-instances-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SearXNG and SearX instances
  introTitle: "Uptime of SearXNG and SearX instances"
  introMessage: This status page monitors [SearXNG and SearX instances](https://github.com/searxng/searx-instances) for uptime.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
