# Change these first
owner: searxng # Your GitHub organization or username, where this repository lives
repo: searx-instances-uptime # The name of this repository
sites:
  - name: searx.space
    url: https://searx.space
  - name: baresearch.org
    url: https://baresearch.org
  - name: copp.gg
    url: https://copp.gg
  - name: darmarit.org
    url: https://darmarit.org/searx
  - name: etsi.me
    url: https://etsi.me
  - name: freesearch.club
    url: https://freesearch.club
  - name: northboot.xyz
    url: https://northboot.xyz
  - name: nyc1.sx.ggtyler.dev
    url: https://nyc1.sx.ggtyler.dev
  - name: ooglester.com
    url: https://ooglester.com
  - name: opnxng.com
    url: https://opnxng.com
  - name: paulgo.io
    url: https://paulgo.io
  - name: priv.au
    url: https://priv.au
  - name: s.mble.dk
    url: https://s.mble.dk
  - name: s.trung.fun
    url: https://s.trung.fun
  - name: search.bus-hit.me
    url: https://search.bus-hit.me
  - name: search.colbster937.dev
    url: https://search.colbster937.dev
  - name: search.datura.network
    url: https://search.datura.network
  - name: search.demoniak.ch
    url: https://search.demoniak.ch
  - name: search.einfachzocken.eu
    url: https://search.einfachzocken.eu
  - name: search.gcomm.ch
    url: https://search.gcomm.ch
  - name: search.hbubli.cc
    url: https://search.hbubli.cc
  - name: search.im-in.space
    url: https://search.im-in.space
  - name: search.in.projectsegfau.lt
    url: https://search.in.projectsegfau.lt
  - name: search.inetol.net
    url: https://search.inetol.net
  - name: search.leptons.xyz
    url: https://search.leptons.xyz
  - name: search.mdosch.de
    url: https://search.mdosch.de
  - name: search.nadeko.net
    url: https://search.nadeko.net
  - name: search.ngn.tf
    url: https://search.ngn.tf
  - name: search.ononoki.org
    url: https://search.ononoki.org
  - name: search.privacyredirect.com
    url: https://search.privacyredirect.com
  - name: search.projectsegfau.lt
    url: https://search.projectsegfau.lt
  - name: search.rhscz.eu
    url: https://search.rhscz.eu
  - name: search.rowie.at
    url: https://search.rowie.at
  - name: search.sapti.me
    url: https://search.sapti.me
  - name: search.smnz.de
    url: https://search.smnz.de
  - name: search.starless.one
    url: https://search.starless.one
  - name: searx.aleteoryx.me
    url: https://searx.aleteoryx.me
  - name: searx.ankha.ac
    url: https://searx.ankha.ac
  - name: searx.ari.lt
    url: https://searx.ari.lt
  - name: searx.baczek.me
    url: https://searx.baczek.me
  - name: searx.be
    url: https://searx.be
  - name: searx.catfluori.de
    url: https://searx.catfluori.de
  - name: searx.daetalytica.io
    url: https://searx.daetalytica.io
  - name: searx.ee
    url: https://searx.ee
  - name: searx.foss.family
    url: https://searx.foss.family
  - name: searx.headpat.exchange
    url: https://searx.headpat.exchange
  - name: searx.juancord.xyz
    url: https://searx.juancord.xyz
  - name: searx.lunar.icu
    url: https://searx.lunar.icu
  - name: searx.namejeff.xyz
    url: https://searx.namejeff.xyz
  - name: searx.nobulart.com
    url: https://searx.nobulart.com
  - name: searx.oakleycord.dev
    url: https://searx.oakleycord.dev
  - name: searx.ox2.fr
    url: https://searx.ox2.fr
  - name: searx.perennialte.ch
    url: https://searx.perennialte.ch
  - name: searx.rhscz.eu
    url: https://searx.rhscz.eu
  - name: searx.sev.monster
    url: https://searx.sev.monster
  - name: searx.si
    url: https://searx.si
  - name: searx.techsaviours.org
    url: https://searx.techsaviours.org
  - name: searx.tuxcloud.net
    url: https://searx.tuxcloud.net
  - name: searx.work
    url: https://searx.work
  - name: searx.zhenyapav.com
    url: https://searx.zhenyapav.com
  - name: searxng.brihx.fr
    url: https://searxng.brihx.fr
  - name: searxng.ca
    url: https://searxng.ca
  - name: searxng.ch
    url: https://searxng.ch
  - name: searxng.online
    url: https://searxng.online
  - name: searxng.site
    url: https://searxng.site
  - name: sex.finaltek.net
    url: https://sex.finaltek.net
  - name: sx.catgirl.cloud
    url: https://sx.catgirl.cloud
  - name: sx.thatxtreme.dev
    url: https://sx.thatxtreme.dev
  - name: sxng.violets-purgatory.dev
    url: https://sxng.violets-purgatory.dev
  - name: twinkpad.pl
    url: https://twinkpad.pl
  - name: www.gruble.de
    url: https://www.gruble.de
  - name: www.jabber-germany.de
    url: https://www.jabber-germany.de/searx
  - name: xo.wtf
    url: https://xo.wtf
  - name: searx.neocities.org
    url: https://searx.neocities.org
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.searxng.org
  #baseUrl: /searx-instances-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SearXNG and SearX instances
  introTitle: "Uptime of SearXNG and SearX instances"
  introMessage: This status page monitors [SearXNG and SearX instances](https://github.com/searxng/searx-instances) for uptime.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
