# Change these first
owner: searxng # Your GitHub organization or username, where this repository lives
repo: searx-instances-uptime # The name of this repository
sites:
  - name: searx.space
    url: https://searx.space
  - name: baresearch.org
    url: https://baresearch.org
  - name: copp.gg
    url: https://copp.gg
  - name: darmarit.org
    url: https://darmarit.org/searx
  - name: etsi.me
    url: https://etsi.me
  - name: northboot.xyz
    url: https://northboot.xyz
  - name: offtheradar.info
    url: https://offtheradar.info
  - name: ooglester.com
    url: https://ooglester.com
  - name: opnxng.com
    url: https://opnxng.com
  - name: paulgo.io
    url: https://paulgo.io
  - name: priv.au
    url: https://priv.au
  - name: s.trung.fun
    url: https://s.trung.fun
  - name: search.0xgingi.com
    url: https://search.0xgingi.com
  - name: search.bowlman.org
    url: https://search.bowlman.org
  - name: search.bus-hit.me
    url: https://search.bus-hit.me
  - name: search.citw.lgbt
    url: https://search.citw.lgbt
  - name: search.cronobox.one
    url: https://search.cronobox.one
  - name: search.demoniak.ch
    url: https://search.demoniak.ch
  - name: search.disroot.org
    url: https://search.disroot.org
  - name: search.dojoro.de
    url: https://search.dojoro.de
  - name: search.fascinated.cc
    url: https://search.fascinated.cc
  - name: search.gcomm.ch
    url: https://search.gcomm.ch
  - name: search.im-in.space
    url: https://search.im-in.space
  - name: search.in.projectsegfau.lt
    url: https://search.in.projectsegfau.lt
  - name: search.kiwitalk.de
    url: https://search.kiwitalk.de
  - name: search.kokomo.cloud
    url: https://search.kokomo.cloud
  - name: search.laksith.dev
    url: https://search.laksith.dev
  - name: search.leptons.xyz
    url: https://search.leptons.xyz
  - name: search.lightinthedark.space
    url: https://search.lightinthedark.space
  - name: search.listi.me
    url: https://search.listi.me
  - name: search.lvkaszus.pl
    url: https://search.lvkaszus.pl
  - name: search.mdosch.de
    url: https://search.mdosch.de
  - name: search.modalogi.com
    url: https://search.modalogi.com
  - name: search.neet.works
    url: https://search.neet.works
  - name: search.ononoki.org
    url: https://search.ononoki.org
  - name: search.projectsegfau.lt
    url: https://search.projectsegfau.lt
  - name: search.rabbit-company.com
    url: https://search.rabbit-company.com
  - name: search.rhscz.eu
    url: https://search.rhscz.eu
  - name: search.rowie.at
    url: https://search.rowie.at
  - name: search.sapti.me
    url: https://search.sapti.me
  - name: search.shininglea.dev
    url: https://search.shininglea.dev
  - name: search.smnz.de
    url: https://search.smnz.de
  - name: search.stinpriza.org
    url: https://search.stinpriza.org
  - name: search.trom.tf
    url: https://search.trom.tf
  - name: search.us.projectsegfau.lt
    url: https://search.us.projectsegfau.lt
  - name: search.whateveritworks.org
    url: https://search.whateveritworks.org
  - name: search.xcloud.live
    url: https://search.xcloud.live
  - name: search.zzls.xyz
    url: https://search.zzls.xyz
  - name: searx.baczek.me
    url: https://searx.baczek.me
  - name: searx.be
    url: https://searx.be
  - name: searx.bissisoft.com
    url: https://searx.bissisoft.com
  - name: searx.catfluori.de
    url: https://searx.catfluori.de
  - name: searx.cthd.icu
    url: https://searx.cthd.icu
  - name: searx.daetalytica.io
    url: https://searx.daetalytica.io
  - name: searx.divided-by-zero.eu
    url: https://searx.divided-by-zero.eu
  - name: searx.doofpot.nl
    url: https://searx.doofpot.nl
  - name: searx.dresden.network
    url: https://searx.dresden.network
  - name: searx.ericaftereric.top
    url: https://searx.ericaftereric.top
  - name: searx.fmac.xyz
    url: https://searx.fmac.xyz
  - name: searx.fossencdi.org
    url: https://searx.fossencdi.org
  - name: searx.juancord.xyz
    url: https://searx.juancord.xyz
  - name: searx.kutay.dev
    url: https://searx.kutay.dev
  - name: searx.mastodontech.de
    url: https://searx.mastodontech.de
  - name: searx.mha.fi
    url: https://searx.mha.fi
  - name: searx.mxchange.org
    url: https://searx.mxchange.org
  - name: searx.namejeff.xyz
    url: https://searx.namejeff.xyz
  - name: searx.netzspielplatz.de
    url: https://searx.netzspielplatz.de
  - name: searx.nixnet.services
    url: https://searx.nixnet.services
  - name: searx.oakleycord.dev
    url: https://searx.oakleycord.dev
  - name: searx.ox2.fr
    url: https://searx.ox2.fr
  - name: searx.perennialte.ch
    url: https://searx.perennialte.ch
  - name: searx.prvcy.eu
    url: https://searx.prvcy.eu
  - name: searx.roflcopter.fr
    url: https://searx.roflcopter.fr
  - name: searx.ru
    url: https://searx.ru
  - name: searx.sev.monster
    url: https://searx.sev.monster
  - name: searx.si
    url: https://searx.si
  - name: searx.thefloatinglab.world
    url: https://searx.thefloatinglab.world
  - name: searx.tiekoetter.com
    url: https://searx.tiekoetter.com
  - name: searx.tuxcloud.net
    url: https://searx.tuxcloud.net
  - name: searx.work
    url: https://searx.work
  - name: searx.zapashcanon.fr
    url: https://searx.zapashcanon.fr
  - name: searx.zhenyapav.com
    url: https://searx.zhenyapav.com
  - name: searxng.ch
    url: https://searxng.ch
  - name: searxng.diadz.de
    url: https://searxng.diadz.de
  - name: searxng.nicfab.eu
    url: https://searxng.nicfab.eu
  - name: searxng.no-logs.com
    url: https://searxng.no-logs.com
  - name: searxng.online
    url: https://searxng.online
  - name: searxng.se
    url: https://searxng.se
  - name: searxng.xcxc.eu
    url: https://searxng.xcxc.eu
  - name: spot.murena.io
    url: https://spot.murena.io
  - name: stalk.antelope.day
    url: https://stalk.antelope.day
  - name: suche.tromdienste.de
    url: https://suche.tromdienste.de
  - name: sx.catgirl.cloud
    url: https://sx.catgirl.cloud
  - name: www.gruble.de
    url: https://www.gruble.de
  - name: www.jabber-germany.de
    url: https://www.jabber-germany.de/searx
  - name: xo.wtf
    url: https://xo.wtf
  - name: searx.neocities.org
    url: https://searx.neocities.org
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.searxng.org
  #baseUrl: /searx-instances-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SearXNG and SearX instances
  introTitle: "Uptime of SearXNG and SearX instances"
  introMessage: This status page monitors [SearXNG and SearX instances](https://github.com/searxng/searx-instances) for uptime.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
