# Change these first
owner: searxng # Your GitHub organization or username, where this repository lives
repo: searx-instances-uptime # The name of this repository
sites:
  - name: searx.space
    url: https://searx.space
  - name: darmarit.org
    url: https://darmarit.org/searx
  - name: de.xcxc.ml
    url: https://de.xcxc.ml
  - name: dynabyte.ca
    url: https://dynabyte.ca
  - name: etsi.me
    url: https://etsi.me
  - name: jackgoss.xyz
    url: https://jackgoss.xyz
  - name: jsearch.pw
    url: https://jsearch.pw
  - name: metasearch.nl
    url: https://metasearch.nl
  - name: northboot.xyz
    url: https://northboot.xyz
  - name: notsearch.uk
    url: https://notsearch.uk
  - name: ooglester.com
    url: https://ooglester.com
  - name: opnxng.com
    url: https://opnxng.com
  - name: paulgo.io
    url: https://paulgo.io
  - name: priv.au
    url: https://priv.au
  - name: privatus.live
    url: https://privatus.live
  - name: s.frlt.one
    url: https://s.frlt.one
  - name: s.trung.fun
    url: https://s.trung.fun
  - name: s.zhaocloud.net
    url: https://s.zhaocloud.net
  - name: saber.tk
    url: https://saber.tk
  - name: search.0relay.com
    url: https://search.0relay.com
  - name: search.affusio.com
    url: https://search.affusio.com
  - name: search.bus-hit.me
    url: https://search.bus-hit.me
  - name: search.chemicals-in-the-water.eu
    url: https://search.chemicals-in-the-water.eu
  - name: search.cronobox.one
    url: https://search.cronobox.one
  - name: search.disroot.org
    url: https://search.disroot.org
  - name: search.drivet.xyz
    url: https://search.drivet.xyz
  - name: search.ethibox.fr
    url: https://search.ethibox.fr
  - name: search.freenetchads.com
    url: https://search.freenetchads.com
  - name: search.gcomm.ch
    url: https://search.gcomm.ch
  - name: search.kiwitalk.de
    url: https://search.kiwitalk.de
  - name: search.mdosch.de
    url: https://search.mdosch.de
  - name: search.mpx.wtf
    url: https://search.mpx.wtf
  - name: search.neet.works
    url: https://search.neet.works
  - name: search.ononoki.org
    url: https://search.ononoki.org
  - name: search.privacyguides.net
    url: https://search.privacyguides.net
  - name: search.projectsegfau.lt
    url: https://search.projectsegfau.lt
  - name: search.rabbit-company.com
    url: https://search.rabbit-company.com
  - name: search.rhscz.eu
    url: https://search.rhscz.eu
  - name: search.rowie.at
    url: https://search.rowie.at
  - name: search.sapti.me
    url: https://search.sapti.me
  - name: search.serginho.dev
    url: https://search.serginho.dev
  - name: search.smnz.de
    url: https://search.smnz.de
  - name: search.snopyta.org
    url: https://search.snopyta.org
  - name: search.stinpriza.org
    url: https://search.stinpriza.org
  - name: search.teamriverbubbles.com
    url: https://search.teamriverbubbles.com
  - name: search.trom.tf
    url: https://search.trom.tf
  - name: search.unlocked.link
    url: https://search.unlocked.link
  - name: search.uspersec.com
    url: https://search.uspersec.com
  - name: search.vidhukant.xyz
    url: https://search.vidhukant.xyz
  - name: search.zzls.xyz
    url: https://search.zzls.xyz
  - name: searx.baczek.me
    url: https://searx.baczek.me
  - name: searx.be
    url: https://searx.be
  - name: searx.becomesovran.com
    url: https://searx.becomesovran.com
  - name: searx.bissisoft.com
    url: https://searx.bissisoft.com
  - name: searx.chocoflan.net
    url: https://searx.chocoflan.net
  - name: searx.divided-by-zero.eu
    url: https://searx.divided-by-zero.eu
  - name: searx.dresden.network
    url: https://searx.dresden.network
  - name: searx.ebnar.xyz
    url: https://searx.ebnar.xyz
  - name: searx.ericaftereric.top
    url: https://searx.ericaftereric.top
  - name: searx.esmailelbob.xyz
    url: https://searx.esmailelbob.xyz
  - name: searx.fi
    url: https://searx.fi
  - name: searx.fmac.xyz
    url: https://searx.fmac.xyz
  - name: searx.fossencdi.org
    url: https://searx.fossencdi.org
  - name: searx.gnous.eu
    url: https://searx.gnous.eu
  - name: searx.gnu.style
    url: https://searx.gnu.style
  - name: searx.juancord.xyz
    url: https://searx.juancord.xyz
  - name: searx.kujonello.cf
    url: https://searx.kujonello.cf
  - name: searx.mastodontech.de
    url: https://searx.mastodontech.de
  - name: searx.mha.fi
    url: https://searx.mha.fi
  - name: searx.mistli.net
    url: https://searx.mistli.net
  - name: searx.mxchange.org
    url: https://searx.mxchange.org
  - name: searx.nakhan.net
    url: https://searx.nakhan.net
  - name: searx.namejeff.xyz
    url: https://searx.namejeff.xyz
  - name: searx.netzspielplatz.de
    url: https://searx.netzspielplatz.de
  - name: searx.nixnet.services
    url: https://searx.nixnet.services
  - name: searx.oakleycord.dev
    url: https://searx.oakleycord.dev
  - name: searx.org
    url: https://searx.org
  - name: searx.orion-hub.fr
    url: https://searx.orion-hub.fr
  - name: searx.priv.pw
    url: https://searx.priv.pw
  - name: searx.prvcy.eu
    url: https://searx.prvcy.eu
  - name: searx.rimkus.it
    url: https://searx.rimkus.it
  - name: searx.ru
    url: https://searx.ru
  - name: searx.run
    url: https://searx.run
  - name: searx.semipvt.com
    url: https://searx.semipvt.com
  - name: searx.sethforprivacy.com
    url: https://searx.sethforprivacy.com
  - name: searx.sev.monster
    url: https://searx.sev.monster
  - name: searx.slipfox.xyz
    url: https://searx.slipfox.xyz/searx
  - name: searx.sp-codes.de
    url: https://searx.sp-codes.de
  - name: searx.stuehieyr.com
    url: https://searx.stuehieyr.com
  - name: searx.tiekoetter.com
    url: https://searx.tiekoetter.com
  - name: searx.tuxcloud.net
    url: https://searx.tuxcloud.net
  - name: searx.tyil.nl
    url: https://searx.tyil.nl
  - name: searx.vanwa.tech
    url: https://searx.vanwa.tech
  - name: searx.webheberg.info
    url: https://searx.webheberg.info
  - name: searx.win
    url: https://searx.win
  - name: searx.xyz
    url: https://searx.xyz
  - name: searx.zapashcanon.fr
    url: https://searx.zapashcanon.fr
  - name: searx.zcyph.cc
    url: https://searx.zcyph.cc
  - name: searxng.dupa.edu.pl
    url: https://searxng.dupa.edu.pl
  - name: searxng.ir
    url: https://searxng.ir
  - name: searxng.nicfab.eu
    url: https://searxng.nicfab.eu
  - name: searxng.zackptg5.com
    url: https://searxng.zackptg5.com
  - name: serx.ml
    url: https://serx.ml
  - name: sh0.it
    url: https://sh0.it
  - name: soek.allesbeste.com
    url: https://soek.allesbeste.com
  - name: spot.murena.io
    url: https://spot.murena.io
  - name: srx.cosmohub.io
    url: https://srx.cosmohub.io
  - name: suche.tromdienste.de
    url: https://suche.tromdienste.de
  - name: swag.pw
    url: https://swag.pw
  - name: sx.catgirl.cloud
    url: https://sx.catgirl.cloud
  - name: timdor.noip.me
    url: https://timdor.noip.me/searx
  - name: trydex.tk
    url: https://trydex.tk/searxng
  - name: wtf.roflcopter.fr
    url: https://wtf.roflcopter.fr/searx
  - name: www.gruble.de
    url: https://www.gruble.de
  - name: www.webrats.xyz
    url: https://www.webrats.xyz
  - name: xcxc.ml
    url: https://xcxc.ml
  - name: xo.wtf
    url: https://xo.wtf
  - name: searx.neocities.org
    url: https://searx.neocities.org
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.searxng.org
  #baseUrl: /searx-instances-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SearXNG and SearX instances
  introTitle: "Uptime of SearXNG and SearX instances"
  introMessage: This status page monitors [SearXNG and SearX instances](https://github.com/searxng/searx-instances) for uptime.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
